### PR TITLE
Issue 382/refactor container creation

### LINKED ISSUE #382: Refactor container creation
### Describe the Current Behavior/Feature:
At the moment, there are several functions that are used to create containers for PASS. Some containers require additional permissions to certain groups.

---
### Proposed Behavior/Feature:
Consolidate container creation to a general function.

### PR DESCRIPTION
**Pull request by leekahung**
## Refactor Container Creation Functions

---
## This PR:
**1.**    Refactors functions for container creation in `src/utils/pod-management/pod-helper.js` into one general function called `createPASSContainer`
**2.**   Removes unused functions from `User.js` and `SignedInUserContext.jsx`
**3.**  Updates unit tests related to these files

---
### Tests
- `test/model-helpers/User.test.js`
- `test/utils/pod-helper.test.js`

### Other Files
- `src/contexts/MessageContext.jsx`
- `src/contexts/SignedInUserContext.jsx`
- `src/model-helpers/User.js`
- `src/utils/pod-management/pod-helper.js`
- `src/utils/index.js`

### CODE REVIEW

**Review by timbot1789 — COMMENTED** [review]
I like this overall. I think it's good

**Comment by xscottxbrownx** [comment]
This looks good to me, but to further my understanding...

Do these containers for `Inbox`, `Outbox`, or `Documents` live within a PASS folder/container to begin with?   Like if user goes to some solid gui will they see a PASS folder and everything is housed inside that?

**Comment by leekahung** [comment]
> This looks good to me, but to further my understanding...
> 
> Do these containers for `Inbox`, `Outbox`, or `Documents` live within a PASS folder/container to begin with?   Like if user goes to some solid gui will they see a PASS folder and everything is housed inside that?

Yeah that is correct, all these containers are containers within a container called PASS.

**Review by xscottxbrownx — APPROVED** [review]

**Comment by leekahung** [comment]
> I like this overall. I think it's good

Is this ready for merging or there's still some things you think we should still do here?

**Pull request merged**
