### PR TITLE
Fixed styling of buttons in InactivityMessage modal

### LINKED ISSUE #492: [Enhancement] - Styling Update for InactivityMessage.jsx
### Describe the Current Behavior/Feature:

At the moment, most of our modals has been converted/"standardized" to use the following style, rounded buttons with the modal action matching the title on the right button:

Screen Shot 2023-11-05 at 19 35 27

Screen Shot 2023-11-05 at 19 35 41

However, one component has yet to be updated, `InactivityMessage.jsx`:

Screen Shot 2023-11-05 at 19 33 43

### Proposed Behavior/Feature:

We can update the styling of `InactivityMessage.jsx`, so that it'll be consistent with the other modals.

### PR DESCRIPTION
**Pull request by JonnyMc94**
## This PR:
Resolves #492  
 
The styling for the buttons in this modal has been updated to be consistent with other modals.

## Screenshots:
Screenshot 2023-11-15 at 17 35 42

### CODE REVIEW

**Review by timbot1789 — APPROVED** [review]

**Review by leekahung — APPROVED** [review]
Think I'm good with the changes made here. Can approve.

Make note of the merge conflict with the `<LogoutButton>`, we've recently updated how we could simply use the `onLogout` prop from the wrapper itself. (See PR https://github.com/codeforpdx/PASS/pull/528).

**Comment by JonnyMc94** [comment]
@leekahung Merge conflict has been resolved

**Comment by leekahung** [comment]
> @leekahung Merge conflict has been resolved

Hey @JonnyMc94 , about the merge conflict, I remember there were only one file that needs updating? Why was all the other files changed as well?

**Comment by leekahung** [comment]
> @leekahung Merge conflict has been resolved

All good. Thanks for the updates👍

**Comment by xscottxbrownx** [comment]
@JonnyMc94 seems Prettier needs to be run...

**Comment by leekahung** [comment]
> @JonnyMc94 seems Prettier needs to be run...

I second @xscottxbrownx suggestion. We got a script set up with prettier: `npm run prettier:run`

**Comment by JonnyMc94** [comment]
@leekahung Should be good to go now!

**Comment by leekahung** [comment]
> @leekahung Should be good to go now!

Got it. Thanks for the updates and contributions to PASS! I'll get this merged in for you along with your other PR. Looks like they're both good to go.

**Pull request merged**
