### PR TITLE
373 husky precommit prettier linter

### LINKED ISSUE #373: Enhancement: Add git hooks to run linter and unit tests
### Describe the Current Behavior/Feature:

We have several automated tests that run on PRs. eslint, prettier, vitests, etc. We don't allow commits to enter the project if these tests don't pass. However, when developing, it can be annoying to run all these manually. It's very easy to forget to run these tests, and only find out you have failures when you create a PR. This slows down code reviews.
Additionally, if a new member is merging from a fork, the PR tests don't run until another maintainer comes by and manually activates them. This makes it difficult to know that they need to run these tests _at all_.

---
### Proposed Behavior/Feature:
A popular package called [Husky](https://www.npmjs.com/package/husky)  is designed to solve these problems. It allows us to run commands on a git commit. If a test fails, the commit is blocked. We can configure this to run `eslint`, `prettier`, and `vitest`. The same commands that are being run in our github workflows.

### PR DESCRIPTION
**Pull request by eathren**
---
name: Pull Request
about: Create a pull request to merge your code into the PASS codebase
title: 'Add Husky precommit hooks to run prettier, linter, and vitest on commit for checks before they reach CI. '
labels: 'husky prettier pre-commit eslint'
assignees: @nolanbraman 

---

## CONCISE description of PR (PR Title)

This runs tests, prettier, and linter before git commit completes

---
## This PR:
**1.**    
**2.** If needed, delete if not    
**3.** If needed, delete if not

---
### Components
All .js, .jsx, .ts, .tsx files and tests

### Tests
This runs all tests on every commit. 

### Other Files
List file names here

---
## Screenshots (if applicable):
Add any screenshots/videos here.

---
## Additional Context (optional):
Add any other context about the PR here.

---
## Future Steps/PRs Needed to Finish This Work (optional):
Add any other steps/PRs that may be needed to continue this work if this PR is just a step in the right direction.

---
## Issues needing discussion/feedback (optional):
**1.**    
**2.** If needed, delete if not    
**3.** If needed, delete if not

### CODE REVIEW

**Comment by leekahung** [comment]
Hey Nolan, with regards to this PR, I'm not too familiar with husky. Was wondering if there would be some pointers in the description as to how this PR is intended to be used with the linting, formatting and testing. Thanks!

**Comment by eathren** [comment]
@leekahung, that is a good point :^)

running `npm run prepare` to install the husky pre-commit hook. I'll go ahead and add a section to the README under installation to help others with this as well, since it is definitely an opt-in feature.

**Review by leekahung — APPROVED** [review]
Have tested out the new changes with Husky. The git hooks seems to work fine to run GitHub actions locally on the terminal with the new instructions on README.md. I can approve this.

**Review by leekahung — DISMISSED** [review]
Actually, I've just ran into some issue with this PR. It seems there's some sort error which I'm not sure what's going on after trying to test out if the linting was working.

Screen Shot 2023-08-25 at 15 57 25

**Comment by andycwilliams** [comment]
Just checking to see if there are any updates with this PR.

**Comment by bingeboy** [comment]
+1 for adding husky

**Comment by aedwardg** [comment]
I'd recommend not running the tests in the pre-commit hook. 1. that would unblock this PR, and 2. it's less likely to slow down development significantly. Requiring all tests to pass before committing can be a roadblock, especially to newer developers.

**Comment by bingeboy** [comment]
IMHO it'd be nice to have testing, linting, and prettier done prior to commit. Having new devs skip testing doesn't sound like an ideal situation since we have limited testing resources and they can always make husky skip testing when pushing to remote for peer review. I've worked both ways in the past... I mainly think have linting and prettier run pre-commit is a nice workflow.

**Comment by timbot1789** [comment]
I think I agree with @aedwardg here. We can add the unit testing hook later if it's useful. Until then, we can remove it and get this unblocked.

**Comment by timbot1789** [comment]
I'll take over and finish up this PR

**Comment by timbot1789** [comment]
I removed the test call from this. Our tests  run oddly slow right now (~40 seconds, but they should run in ~4 seconds), and I don't think we need to run that on every commit. If someone likes committing work frequently, that delay could get annoying.

We can consider adding it back in once we figure out what's causing tests to run so slowly.

**Comment by timbot1789** [comment]
@leekahung can you review again?

**Comment by leekahung** [comment]
> @leekahung can you review again?

I don't have my computer with me on my trip, so I couldn't really check if the fixes are good on my end. But if you guys think this is ready, I'm good with approving this.

**Comment by timbot1789** [comment]
> > @leekahung can you review again?
> 
> I don't have my computer with me on my trip, so I couldn't really check if the fixes are good on my end. But if you guys think this is ready, I'm good with approving this.

Ah ok. In that case I'll just dismiss your change request and merge it.

**Review by timbot1789 — APPROVED** [review]

**Pull request merged**
