### PR TITLE
Fix typo in ci.yml

### PR DESCRIPTION
**Pull request by k-mack**
Found a typo in `ci.yml` that is likely preventing the Deploy workflow from running on Master.

Relates to #20.

### CODE REVIEW

**Comment by k-mack** [comment]
I had to revert some previous changes that removed `package-lock.json` from the repo. This file should be source controlled. See https://docs.npmjs.com/cli/v6/configuring-npm/package-locks#using-locked-packages for more on that.

**Comment by leekahung** [comment]
Looks good! Build check is back on green.

**Review by leekahung — APPROVED** [review]

**Comment by k-mack** [comment]
Thanks!

**Comment by leekahung** [comment]
Latest changes from issue-20/fix-typo has been merged into Development. Can remove safely.

**Pull request merged**
