### PR TITLE
Remove user activity

### PR DESCRIPTION
**Pull request by timbot1789**

### CODE REVIEW

**Comment by xscottxbrownx** [comment]
### What was the reasoning for this whole thing again?

Was it just no real utility to show this in the table?   

Would there be any other reason now or in future to need to know this "last activity" time, even if not to display to user but to keep the functionality for other dev purposes?

**Comment by timbot1789** [comment]
> ### What was the reasoning for this whole thing again?
> Was it just no real utility to show this in the table?
> 
> Would there be any other reason now or in future to need to know this "last activity" time, even if not to display to user but to keep the functionality for other dev purposes?

No immediate utility in the table, and a pretty substantial performance degradation. Probably what we need instead here is a Client Profile stored on the client's pod that we fetch, but that's not really what this data point does.

**Comment by xscottxbrownx** [comment]
I don't see any issues.  I would like @leekahung 's eyes on the modal-helpers files though.

**Review by leekahung — APPROVED** [review]
I think it should be fine.

We're going to move over the storing of the last active date inside the user's profile card. Could get the time from there once that completes.

**Comment by leekahung** [comment]
Think we can merge this after the branch updates. @timbot1789 

Let me know if you think it's ready. 👍

**Pull request merged**
