### PR TITLE
Disable Button when application runs

### LINKED ISSUE #53: Disable button while application is running to upload/fetch/querying file form Pod
**Is your feature request related to a problem? Please describe.**
To prevent extraneous request, it might be good to disable the button for specific form while it's running the request

**Describe the solution you'd like**
Include action as part of statusReducer

**Describe alternatives you've considered**
None

**Additional context**
None

### PR DESCRIPTION
**Pull request by leekahung**
- Correcting JSDoc for statusReducer (which is suppose to be file property, not clearValue)
- Included processing property to useStatusNotificationObject
- Changed reducer to return only action of specific property when called
- Included SET_PROCESSING and CLEAR_PROCESSING to components and runNotification function

### CODE REVIEW

**Comment by leekahung** [comment]
This will add function that disable button while application is processing request to upload/query/delete files from Solid; Will be enabled again after its processed

Aim of this is to reduce potential multiple of the same request from being sent to Solid

As a side, also fixed JSDoc for statusReducer

**Comment by Jared-Krajewski** [comment]
not sure if this is working as intended, I Haven't had a chance to troubleshoot why but it still allows spam submissions when I cloned and ran it.

**Comment by leekahung** [comment]
No, you are correct. At the moment, this feature is still a little buggy. Trying to figure out the positioning on where I set the button disabled state within runNotification and the handler functions in the Forms.

**Comment by leekahung** [comment]
Did a few fixes and refactoring for runNotification and the Form handler functions. Think it should be working now.

**Pull request merged**
