### PR TITLE
 Add notification for inaccessible documents

### LINKED ISSUE #694: [Enhancement] - Add notification for inaccessible data
### Describe the Current Behavior/Feature:

User 1 gave User 2 access to one of their documents and later revoked access to it. However, User 2 still sees that document in their list. When User 2 then tries to access it, nothing appears to happen. With no feedback they might think something is broken.

### Rationale:

There is feedback provided in the console but not for the user themselves. This is neither accessible nor user-friendly design. The user ought to be informed when something does not work as they intended it.

### Proposed Changes:

There is already a custom hook called `useNotification.js`. Import that and alert the user whenever something is no longer accessible.

### PR DESCRIPTION
**Pull request by omarNaifer12**
## This PR:
Resolves #694 
**1.**    
**2.** If needed, delete if not    
**3.** If needed, delete if not

## Screenshots (if applicable):
Add any screenshots/videos here.
screenShotNotification

## Additional Context (optional):
Add any other context about the PR here.
I added a try-catch block to the handleShowDocumentLocal function in the DocumentTable component to handle the case where a user doesn't have access to a document. If a 403 error occurs (Unauthorized), the catch block triggers a notification informing the user they don't have permission to view the document.

@Jared-Krajewski @timbot1789 @xscottxbrownx @leekahung 

Please review the changes and let me know if there are any adjustments or improvements needed.

## Future Steps/PRs Needed to Finish This Work (optional):
Add any other steps/PRs that may be needed to continue this work if this PR is just a step in the right direction.

## Issues needing discussion/feedback (optional):
**1.**    
**2.** If needed, delete if not    
**3.** If needed, delete if not

### CODE REVIEW

**Comment by andycwilliams** [comment]
This is working so far from my testing. However, I hesitate approving it just yet because it involves interaction with Solid and I have less experience on that aspect of the app. I'd like to wait for input from the development side and then can approve.

Thank you for your efforts!

**Comment by omarNaifer12** [comment]
@andycwilliams  Thank you for your review! I’ll wait for the approval.

**Review by leekahung — APPROVED** [review]
This looks like a good try catch. Can approve for merging 👍

**Comment by omarNaifer12** [comment]
@leekahung Yes, thank you. I was trying to find a way to do this without it since it's not used much in the project, but I couldn't find one because it gives an error and needs to be addressed.

**Pull request merged**
