### PR TITLE
I've removed the inaccurate lines for renderWebId and AddContactModal…

### LINKED ISSUE #422: Incorrect jsDoc comments in `AddContactModal.jsx`
### Bug Title:
Fix incorrect jsDoc in `AddContactModal.jsx`

---
### Bug Description:
The jsDoc for `renderWebId` function at top of file is inaccurate.
The jsDoc for `AddContactModal` is inaccurate.

### PR DESCRIPTION
**Pull request by mallick03**
## Editing jsDoc's for AddContactModal

---
## This PR:
Resolves #422 
 
**1.**    
**2.** If needed, delete if not    
**3.** If needed, delete if not

### CODE REVIEW

**Comment by xscottxbrownx** [comment]
I'm honestly fairly new with jsdoc, but why removing the `@name`'s?

**Comment by leekahung** [comment]
I believe you originally meant fixing the `@param` tags @xscottxbrownx in #422?

**Comment by xscottxbrownx** [comment]
> I believe you originally meant fixing the `@param` tags @xscottxbrownx in #422?

Honestly, I'm not sure... I should've screenshot what was there at the time of writing up the issue.  

Looking at them now, I'm not sure the params are incorrect. But, I've never seen us write them this way (that they are the React `props` object.) Not sure it's wrong though.

**Comment by bingeboy** [comment]
LGTM but looks like the description of the PR needs a little updating.

**Review by timbot1789 — APPROVED** [review]

**Comment by andycwilliams** [comment]
It looks like this is both from a forked repo and is merging into the master branch. We merge into the development branch before initiating larger merges into master.

**Comment by xscottxbrownx** [comment]
> It looks like this is both from a forked repo and is merging into the master branch. We merge into the development branch before initiating larger merges into master.

Agreed, this needs to go into development.

**Review by andycwilliams — CHANGES_REQUESTED** [review]
Merged branch needs to be changed from Master to Development

**Comment by timbot1789** [comment]
@mal092 this has been inactive for 3 weeks. Will you be able to return to this soon?

**Comment by timbot1789** [comment]
@mal092 This PR has been inactive for 1 month, with no activity. We will be closing it. If you would like to reopen it, you can reach out in the dev channel on our discord.

**Pull request closed without merging**
