### PR TITLE
Fix links in pod registration card

### LINKED ISSUE #645: [Bug Report] - HTML incorrectly rendered in new pod page
### Describe the bug:
After creating a new pod, the user is redirected to a landing page where a few links are shown. Those links are incorrectly rendered so the <a></a> tags are visible to the user.

### Expected behavior:
The page should show clickable links rather than HTML as text on the screen.

### Actual Behavior:
See the screenshot.

### Screenshots:
Screenshot_20240521_184038

### To Reproduce:
1. Go to the main page
2. Click on sign up
3. Enter new credentials
4. See some HTML rendered as text

### Possible Fix:
Should be simple to reformat the HTML a bit.

### PR DESCRIPTION
**Pull request by AJSterner**
## This PR:
Resolves #645 

The pod registration page wasn't registering the pod links correctly! Now it does.

## Screenshots (if applicable):
**Before**
Screenshot_20240521_184038
**After**
Screenshot_20240528_182502

### CODE REVIEW

**Review by leekahung — APPROVED** [review]
Don't want to be too picky on this since it looks like it's working, but was wondering if we should start replacing the existing `<br />` with `<span>`/`<p>` elements or include styling to the MUI `<Typography />` components so that we have more control over spacing/padding/margins in the future in case we want to update them.

Other than that, can approve this change.

**Comment by andycwilliams** [comment]
> Don't want to be too picky on this since it looks like it's working, but was wondering if we should start replacing the existing `<br />` with `<span>`/`<p>` elements or include styling to the MUI `<Typography />` components so that we have more control over spacing/padding/margins in the future in case we want to update them.
> 
> Other than that, can approve this change.

That definitely should be done but I'm fine with leaving it for another PR as this one is pretty focused. And these might already be covered by #587. Otherwise we can create a new issue.

**Comment by leekahung** [comment]
Think we can merge this for now then. 👍

**Comment by AJSterner** [comment]
image
Updated to use MUI!

**Pull request merged**
