### PR TITLE
update outbox recipient text

### LINKED ISSUE #693: [Enhancement] - Replace "Sender" with "Recipient" in Outbox
### Describe the Current Behavior/Feature:

On the Messages page, it states who sent a given message. This works for the Inbox but for the Outbox the effect is simply repeating the user's own name.

Inbox for user named Samuel Foster:

Outbox for user named Samuel Foster:

### Rationale:

It would be more informative and intuitive if it stated who received the user's messages. The user does not need to be told they sent each message in the Outbox.

### Proposed Changes:

- Replace the "Sender" field in Outbox with "Recipient"

### PR DESCRIPTION
**Pull request by oddwili**
## This PR:
Resolves #693 

## Screenshots (if applicable):

Screen Shot 2024-11-18 at 12 24 25 PM

### CODE REVIEW

**Comment by andycwilliams** [comment]
I can take a closer look at this later but for now just wanted to request fixing the tests. We'll need that before ultimately approving.

Thanks for your effort!

**Comment by oddwili** [comment]
updated and added tests and ran prettier

**Review by leekahung — APPROVED** [review]
Saw the changes for the Outbox when building with this branch. This looks good to me. 👍

**Review by andycwilliams — APPROVED** [review]
lgtm

**Pull request merged**
