### PR TITLE
Issue 635/discovery landing page styling adjustments

### LINKED ISSUE #635: [Discovery] - Landing page styling adjustments
### Describe the Current Behavior/Feature:

A few possible, small adjustments. Each one is related to `KeyFeatures.jsx`.

1. The primary theme color has changed from a green to a blue, but the images used on the landing page have not been updated.
2. Refactor the icons to fit on smaller screens. Currently, at least one icon looks strangely to the side when on a mobile viewport. 
3. Several minor optimizations for Material UI. See below for specifics.

On a small viewport:
IconIsKindOfOffCenterAndImagesAreStillGreen

On a slightly larger viewport:

### Rationale:

1. The images should continue to match the theme.
2. Minor visual improvement.
3. Helps maintain consistency, matching how styling is handled elsewhere.

### Proposed Changes:

1. Replace the images with versions that match the theme.
2. Could possibly make them conditionally render as a column rather than a row. Or by adjusting the titles themselves.
3. Line 40 in `KeyFeatures.jsx` can be refactored from using `<strong>` to simply adding `fontWeight` in the Typography `sx`. Additionally, in Material UI components `marginBottom` can be simplified as `mb` (lines 27 and 48).

### PR DESCRIPTION
**Pull request by dbmzzo**
## This PR:
Resolves #635 - Landing page styling adjustments
 
**1.** Changes green homepage `png` images to blue `webp` files.
**2.** Fixes key features icon layout issues by switching to column layout on narrow viewports

## Screenshots:
Screenshot 2024-06-28 at 10 17 23 AM
Screenshot 2024-06-28 at 10 17 17 AM
Screenshot 2024-06-28 at 10 17 08 AM

Screenshot 2024-06-28 at 10 15 26 AM

### CODE REVIEW

**Review by andycwilliams — APPROVED** [review]
Looks good to me! I had marked this issue as Discovery and not MVP but am glad to have it done. Makes the app that much more presentable.

**Review by leekahung — CHANGES_REQUESTED** [review]
If we are going to place images in the repo, would like to have the image file sizes to get smaller rather than larger. Could we have these images converted into `.webp`? Either that or have smaller PNGs.

**Comment by dbmzzo** [comment]
> If we are going to place images in the repo, would like to have the image file sizes to get smaller rather than larger. Could we have these images converted into `.webp`? Either that or have smaller PNGs.

Good catch! I replaced the PNG files with WEBP for a significant file size reduction.

**Review by leekahung — APPROVED** [review]

**Comment by leekahung** [comment]
Alright, think I could merge this in. The PR looks good already and is approved.

**Pull request merged**
