### PR TITLE
Add Contact - changing client terminology to contact

### LINKED ISSUE #425: Add Contact still showing "client"
### Bug Title:
Some items still show as `client` instead of `contact`

---
### Bug Description:
When adding a contact, the modal button says `ADD CLIENT`.
After adding a contact, the success notification says `added to client list`.

---
### Reproduction Steps:    
**1.**  Navigate to `contacts` page
**2.** Click red `ADD CONTACT` button

---
### Expected Behavior:
Anything with `client` should now be `contact`

---
### Screenshots (If applicable):
Screenshot 2023-09-14 at 9 15 20 PM

Screenshot 2023-09-14 at 9 15 38 PM

---
### Additional Context (optional):
These are just a few things I found that we have missed when changing terminology.

### PR DESCRIPTION
**Pull request by xscottxbrownx**
## Add Contact "client" --> "contact"

---
## This PR:
Resolves #425 

**1.**  Changes confirm button to `ADD CONTACT` 
**2.** Changes success notification to `...added to contact list` 

---
### Components
`AddContactModal.jsx`

### Tests
List file names here

### Other Files
List file names here

---
## Screenshots (if applicable):
Screenshot 2023-09-14 at 9 25 16 PM

Screenshot 2023-09-14 at 9 25 34 PM

### CODE REVIEW

**Comment by andycwilliams** [comment]
Putting 'client' in search for the whole repo yields a lot of results. Will be want to change every instance of it, and if so, will we want it in the scope of this PR?

If not, this should be good to go.

**Review by leekahung — APPROVED** [review]
I'm good with this change. Approving.

**Comment by leekahung** [comment]
> Putting 'client' in search for the whole repo yields a lot of results. Will be want to change every instance of it, and if so, will we want it in the scope of this PR?

That would not be a good idea. For example, React Query utilizes a parameter called `client` that's not related to the PASS `client`. We could do this correction on a case-by-case basis.

**Comment by xscottxbrownx** [comment]
I could change the name of the issue and this PR to more directly reference the ADD CONTACT modal, if we'd like.

**Comment by xscottxbrownx** [comment]
> I could change the name of the issue and this PR to more directly reference the ADD CONTACT modal, if we'd like.

Oh I guess I did on the Issue, so I'll change it here.

**Review by andycwilliams — APPROVED** [review]
With the more focused scope this all done

**Pull request merged**
