### PR TITLE
622 standardize all input fields

### LINKED ISSUE #622: [Enhancement] - Standardize all input fields in multiple modals
### Describe the Current Behavior/Feature:

Currently, many of the margins between each input in the Add Contact, New Message, and Reply To modals are different sizes. They should be equidistant.

### Rationale:
Sizing should be more consistent and standardized. See the Upload Document modal for an example of the desired result:

### Proposed Changes:

Apply the same standardization of margin to the Add Contact and New Message modals.

### PR DESCRIPTION
**Pull request by DionSat**
## This PR:
Resolves #622 
 
**1.**   Standardize New Message Modal 
**2.**   Standardize Add Contact Modal
**3.**   Standardize Upload Document Modal

## Screenshots (if applicable):
image

image

image

### CODE REVIEW

**Comment by andycwilliams** [comment]
Only just noticing this. When using different browsers I got different margins for the same modal.

Chromium:


Firefox:


Haven't looked too much into this, but it may have to do with that modal using `<br>` rather than setting the margins as "normal" the way other ones do. Add Contact uses `margin="normal"` rather than `<br>` and looks the same on both browsers.

**Comment by DionSat** [comment]
Thanks for finding that. This is why I didn't want to finalize the PR yet. Because there are different modals I haven't checkout yet. I'll be sure to check that out and see if I can find any other issues once I'm back from work.

**Comment by andycwilliams** [comment]
> Thanks for finding that. This is why I didn't want to finalize the PR yet. Because there are different modals I haven't checkout yet. I'll be sure to check that out and see if I can find any other issues once I'm back from work.

A long while back we were talking about not using `<br />`s and just use MUI's styling. But we never really settled on a plan so it's become a hodgepodge. This would be a good opportunity to standardize them.

**Comment by DionSat** [comment]
I just decided to remove all the ```<br />``` tags from the modals. It seems to be running fine on my firefox and chrome. Hopefully thats everything I'll be moving this over to review.

**Comment by leekahung** [comment]
I'm in favor of using styling/CSS to adjust for spacing over `<br />` since we'll have more control over margin and padding sizes.

**Review by andycwilliams — APPROVED** [review]
Nice work!

**Pull request merged**
