### PR TITLE
Updating "No Contacts Found" to use appropriate tag

### LINKED ISSUE #518: Bug: (Contacts) "No contacts found" using `h2` for content instead of organization
### Bug Description:

When no contacts are found, the main content ("No contacts found") uses an `h2` instead of something more semantically appropriate. Headings should be used for navigation, not for content.

### Reproduction Steps:    

**1.** Log in to an account that has no contacts.
**2.** Go to the Contacts tab.
**3.** Observe the DOM of the content ("No contacts found").

### Expected Behavior:

The content should be something like a `p` tag or similar.

### Screenshots (If applicable):

The Contacts tab of a logged in user, showing 'No contacts found' prominently in the center.

### Additional Context (optional):

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#navigation

### Possible Solution (optional):

* Make the heading above the list of contacts an actual `h2` element. For navigation with assistive technology, this will show someone "this is where the contacts are/will be"; when they go there, they will find that there are no contacts available. This will give a consistent experience regardless if contacts exist or not.
* Change the element for the text to something that is meant for dynamic content, like a `p` tag.

### PR DESCRIPTION
**Pull request by JonnyMc94**
## This PR:
Resolves #518 
 
Reproduction Steps:
1. Log in to an account that has no contacts.
2. Go to the Contacts tab.
3. Observe the DOM of the content ("No contacts found").

Result - The content is now contained in a `<p>`  tag. Additionally, as suggested in the Possible Solution, the element containing "Contacts", below the Navbar, has now been updated from a `<p>` to a `<h2>` tag.

### CODE REVIEW

**Comment by xscottxbrownx** [comment]
so what would be the `h1` of this page?

**Comment by JonnyMc94** [comment]
I see that there is a separate issue raised for that problem here - https://github.com/codeforpdx/PASS/issues/519

I'm not sure I see a very suitable candidate for a h1 in the markup. It should provide context as to the page content from an accessibility standpoint. I can back the changes to `Breadcrumbs.jsx` out of this PR until a solid decision on heading structure has been made if necessary?

**Comment by xscottxbrownx** [comment]
> I see that there is a separate issue raised for that problem here - #519
> 
> I'm not sure I see a very suitable candidate for a h1 in the markup. It should provide context as to the page content from an accessibility standpoint. I can back the changes to `Breadcrumbs.jsx` out of this PR until a solid decision on heading structure has been made if necessary?

No don’t take anything out of this pr.   It was an honest question. Do you feel there breadcrumbs could be the `h1`?

seems many of us are finding issues with the markup, and i was pondering what to do on the other non-home pages for this issue.

**Comment by andycwilliams** [comment]
Hi @JonnyMc94, thanks for contributing.

Quick question, in the issue you ask @milofultz to collaborate on this. Did you receive a response saying so? Just want to make sure existing assignees for issues are aware of what's happening and able to respond.

**Comment by JonnyMc94** [comment]
> > I see that there is a separate issue raised for that problem here - #519
> > I'm not sure I see a very suitable candidate for a h1 in the markup. It should provide context as to the page content from an accessibility standpoint. I can back the changes to `Breadcrumbs.jsx` out of this PR until a solid decision on heading structure has been made if necessary?
> 
> No don’t take anything out of this pr. It was an honest question. Do you feel there breadcrumbs could be the `h1`?
> 
> seems many of us are finding issues with the markup, and i was pondering what to do on the other non-home pages for this issue.

Ok. To be honest, the breadcrumb probably provides the most context and would make the most sense to be the h1! This same fix would then need to be applied to other pages with a similar layout.

**Comment by JonnyMc94** [comment]
> Hi @JonnyMc94, thanks for contributing.
> 
> Quick question, in the issue you ask @milofultz to collaborate on this. Did you receive a response saying so? Just want to make sure existing assignees for issues are aware of what's happening and able to respond.

I hadn't realised that it was assigned. I was interested in diving into the code base and just spotted this as a nice first contribution. I will hold off until I get a response in future. If @milofultz was working on this I've no issue with the PR being closed, that's my mistake.

**Comment by andycwilliams** [comment]
> > Hi @JonnyMc94, thanks for contributing.
> > Quick question, in the issue you ask @milofultz to collaborate on this. Did you receive a response saying so? Just want to make sure existing assignees for issues are aware of what's happening and able to respond.
> 
> I hadn't realised that it was assigned. I was interested in diving into the code base and just spotted this as a nice first contribution. I will hold off until I get a response in future. If @milofultz was working on this I've no issue with the PR being closed, that's my mistake.

There's an "Assignees" section in each issue where you can see if anyone has claimed the issue yet. If no one is assigned, it's okay for people to assign themselves. However, if it's already assigned to someone, let them know you're also interested and see if they need help.

**Comment by milofultz** [comment]
> > Hi @JonnyMc94, thanks for contributing.
> > Quick question, in the issue you ask @milofultz to collaborate on this. Did you receive a response saying so? Just want to make sure existing assignees for issues are aware of what's happening and able to respond.
> 
> I hadn't realised that it was assigned. I was interested in diving into the code base and just spotted this as a nice first contribution. I will hold off until I get a response in future. If @milofultz was working on this I've no issue with the PR being closed, that's my mistake.

All good, have at it!

**Comment by milofultz** [comment]
> > > I see that there is a separate issue raised for that problem here - #519
> > > I'm not sure I see a very suitable candidate for a h1 in the markup. It should provide context as to the page content from an accessibility standpoint. I can back the changes to `Breadcrumbs.jsx` out of this PR until a solid decision on heading structure has been made if necessary?
> > 
> > 
> > No don’t take anything out of this pr. It was an honest question. Do you feel there breadcrumbs could be the `h1`?
> > seems many of us are finding issues with the markup, and i was pondering what to do on the other non-home pages for this issue.
> 
> Ok. To be honest, the breadcrumb probably provides the most context and would make the most sense to be the h1! This same fix would then need to be applied to other pages with a similar layout.

My thought with "Contacts" being an `h2` is that the page people are landing in here should probably be called something and use _that_ as the `h1`. And then the _tabs_ have their own `h2`s inside (in this case, "Contacts"). Don't know the name of the larger page per se (shit examples: "Logged In User Page", "User Information", "Dashboard", I dunno).

**Comment by JonnyMc94** [comment]
> > > > I see that there is a separate issue raised for that problem here - #519
> > > > I'm not sure I see a very suitable candidate for a h1 in the markup. It should provide context as to the page content from an accessibility standpoint. I can back the changes to `Breadcrumbs.jsx` out of this PR until a solid decision on heading structure has been made if necessary?
> > > 
> > > 
> > > No don’t take anything out of this pr. It was an honest question. Do you feel there breadcrumbs could be the `h1`?
> > > seems many of us are finding issues with the markup, and i was pondering what to do on the other non-home pages for this issue.
> > 
> > 
> > Ok. To be honest, the breadcrumb probably provides the most context and would make the most sense to be the h1! This same fix would then need to be applied to other pages with a similar layout.
> 
> My thought with "Contacts" being an `h2` is that the page people are landing in here should probably be called something and use _that_ as the `h1`. And then the _tabs_ have their own `h2`s inside (in this case, "Contacts"). Don't know the name of the larger page per se (shit examples: "Logged In User Page", "User Information", "Dashboard", I dunno).

~Ok, so would I be right in assuming that that creating a contextual title in a h1 tag for these types of pages can be logged as a separate issue?~

This issue was created to address the problem right? #519

**Comment by xscottxbrownx** [comment]
> > > > I see that there is a separate issue raised for that problem here - #519
> > > > I'm not sure I see a very suitable candidate for a h1 in the markup. It should provide context as to the page content from an accessibility standpoint. I can back the changes to `Breadcrumbs.jsx` out of this PR until a solid decision on heading structure has been made if necessary?
> > > 
> > > 
> > > No don’t take anything out of this pr. It was an honest question. Do you feel there breadcrumbs could be the `h1`?
> > > seems many of us are finding issues with the markup, and i was pondering what to do on the other non-home pages for this issue.
> > 
> > 
> > Ok. To be honest, the breadcrumb probably provides the most context and would make the most sense to be the h1! This same fix would then need to be applied to other pages with a similar layout.
> 
> My thought with "Contacts" being an `h2` is that the page people are landing in here should probably be called something and use _that_ as the `h1`. And then the _tabs_ have their own `h2`s inside (in this case, "Contacts"). Don't know the name of the larger page per se (shit examples: "Logged In User Page", "User Information", "Dashboard", I dunno).

Ok, that's something to discuss then - currently Contacts and Civic Profile are completely different pages/routes.
Screenshot 2023-11-21 at 9 33 41 AM

**Comment by leekahung** [comment]
Hey @JonnyMc94 @milofultz what's the progress of this PR? Has you two decide how to proceed with the `<h_>` tags for the different pages?

Have saw the discussions on Issues #518 and #519 and the work in PR #531. Let me know.

**Comment by JonnyMc94** [comment]
@leekahung There hasn't been a final decision as far as I'm aware. This code be merged and then the issue of `h1` tag for each page addressed subsequently? From the discussion above I think a decision on what the `h1` is going to be for this page and others like it

**Comment by leekahung** [comment]
> @leekahung There hasn't been a final decision as far as I'm aware. This code be merged and then the issue of `h1` tag for each page addressed subsequently? From the discussion above I think a decision on what the `h1` is going to be for this page and others like it

Got it. If that's the case think I can approve. The updates here looks alright.

**Review by leekahung — APPROVED** [review]
Approved.

**Pull request merged**
