### PR TITLE
Issue-444 / fix alt typo for images

### LINKED ISSUE #444: [BUG] - typo in alt of HomeSection.jsx
### Bug Description:
The images used in `HomeSection.jsx` should have alt tags for accessibility and seo, but the are misspelled to `lt` so are not working as intended.

---
### Expected Behavior:
Replace typo with `alt` so it will work as intended.

### PR DESCRIPTION
**Pull request by xscottxbrownx**
## This PR:
Resolves #444 
 
**1.**   Replaces `lt` typo with `alt`

### CODE REVIEW

**Comment by bingeboy** [comment]
Once `test/pages/__snapshots__/Home.test.jsx.snap` is updated for the test to pass this LGTM 👍

**Review by andycwilliams — APPROVED** [review]
The test still needs to pass, but it's such a quick fix I'm okay with approving it now so it can be merged once that's done.

**Review by ogorman89 — APPROVED** [review]
Looks good. See @andycwilliams  & @bingeboy notes on the Home.test snapshot.

**Comment by xscottxbrownx** [comment]
Thanks all, I'll need to dig into this - I was under the impression it wasn't good practice to use snapshots when unit testing front-end react code.  I missed this entirely.

**Review by timbot1789 — CHANGES_REQUESTED** [review]
Looks like this is causing a test failure. You'll need to fix that before we can merge this.

**Comment by timbot1789** [comment]
> Thanks all, I'll need to dig into this - I was under the impression it wasn't good practice to use snapshots when unit testing front-end react code. I missed this entirely.

I added some snapshots in older tests when we were first writing the tests, since we used them at my last job a lot. I've come to agree though that snapshots aren't particularly useful. You can remove it if you want, but I'd ask you add some other tests in that show the intended behavior of the component (RTL stuff)

**Comment by xscottxbrownx** [comment]
> Looks like this is causing a test failure. You'll need to fix that before we can merge this.

Got snapshot updated and passing.

**Review by timbot1789 — APPROVED** [review]

**Pull request merged**
